# Generated by Django 5.2.8 on 2025-12-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='description',
            field=models.TextField(blank=True, help_text='Bu derste neler anlatacaksın? Yöntemin nedir?', verbose_name='Ders Açıklaması'),
        ),
    ]
