# Generated by Django 5.2.8 on 2025-12-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userskill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_rewarded',
            field=models.BooleanField(default=False, verbose_name='Referans Ödülü Verildi mi?'),
        ),
    ]
