# Generated by Django 5.2.8 on 2025-12-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Admin Onayı Bekliyor'), ('approved', 'Onaylandı / Aktif'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('active', 'Onaylı / Aktif'), ('suspended', 'Askıya Alındı')], default='pending', max_length=20)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('used_referral', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
