# Generated by Django 5.2.8 on 2025-12-27 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_session_status_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='certificate',
            field=models.FileField(null=True, upload_to='certificates/', verbose_name='Sertifika/Belge'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylandı mı?'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Admin Onayı Bekliyor'), ('pending_tutor', 'Hoca Onayı Bekliyor'), ('approved', 'Onaylandı / Aktif'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
