# Generated by Django 5.2.8 on 2025-12-27 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_is_rewarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
