# Generated by Django 5.2.8 on 2025-12-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userskill_certificate_userskill_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='location',
            field=models.CharField(choices=[('online', '🌐 Online (Zoom / Google Meet)'), ('tutor_home', '🏠 Kendi Evimde'), ('student_home', '🎒 Öğrencinin Evinde'), ('campus', '🏫 Kampüs / Ortak Alan')], default='online', max_length=20, verbose_name='Dersin İşleneceği Yer'),
        ),
    ]
