# Generated by Django 5.2.8 on 2026-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('general', 'General Discussion'), ('campus', 'Campus Life & Events'), ('tech', 'Technology & Coding'), ('study', 'Study Tips & Resources'), ('career', 'Career & Internship'), ('social', 'Social & Fun')], default='general', max_length=20),
        ),
    ]
