# Generated by Django 5.2.8 on 2025-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_rewarded',
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('active', 'Aktif')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='description',
            field=models.TextField(blank=True, verbose_name='Ders Açıklaması'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='location',
            field=models.CharField(choices=[('online', '🌐 Online'), ('tutor_home', '🏠 Kendi Evimde'), ('student_home', '🎒 Öğrencinin Evinde'), ('campus', '🏫 Kampüs')], default='online', max_length=20),
        ),
    ]
