# Generated by Django 5.2.8 on 2025-12-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_profile_is_rewarded_alter_message_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_rewarded',
            field=models.BooleanField(default=False, verbose_name='Referans Ödülü Verildi mi?'),
        ),
    ]
